### ISSUE TITLE
 Error: Child compilation failed:

### ISSUE THREAD

**Issue by PlusLius** [wuomzfx/html-layout-loader#1]
问题: html-layout-loader使用不是很明确,如果是配置不正确,该如何正确使用loader

目录结构:
![image](https://user-images.githubusercontent.com/23534665/31571613-ebc2e28e-b0c8-11e7-9c74-7210ef4e7ce8.png)

webpack.config.js配置
![image](https://user-images.githubusercontent.com/23534665/31571673-ee791344-b0c9-11e7-81f3-458b9c2a0186.png)

index.html配置
![image](https://user-images.githubusercontent.com/23534665/31571664-bb6c74b4-b0c9-11e7-8929-0d5608875b03.png)

a.html配置
![image](https://user-images.githubusercontent.com/23534665/31571681-0807a884-b0ca-11e7-9a08-49ca70a20a9a.png)

报错信息:
![image](https://user-images.githubusercontent.com/23534665/31571676-f9ee4898-b0c9-11e7-8683-f1ee79df48c6.png)

**Comment by wuomzfx** [comment]
你options.layout 路径填错啦

**Comment by wuomzfx** [comment]
另外，看你的文件，应该是 index.html 才是模版文件，a.html是入口文件 @PlusLius

**Comment by PlusLius** [comment]
@wuomzfx 好的,谢谢! 已经找到原因了

**Comment by baoyadong** [comment]
@wuomzfx ,我的文件结构和上面是一样的，有两个问题：
1. 这个options.layout的路径应该是咋样的？
2.我直接报这个错，你看下什么情况？
<img width="711" alt="2018-01-02 10 08 25" src="https://user-images.githubusercontent.com/24292531/34486220-b189e736-f009-11e7-9f1d-8b59e7e52b87.png">

**Comment by wuomzfx** [comment]
@baoyadong html-layout.loader ??? 写错了吧，应该是 html-layout-loader

**Comment by baoyadong** [comment]
这个改过了，但是还报错。我的页面结构和内容和上面是一样的，就是webpack.config.js配置如下：

<img width="537" alt="2018-01-03 8 54 59" src="https://user-images.githubusercontent.com/24292531/34506028-421a67b2-f064-11e7-90a3-392afddbadf0.png">
然后报错如下：
<img width="475" alt="2018-01-03 8 58 57" src="https://user-images.githubusercontent.com/24292531/34506043-5fbceea2-f064-11e7-8180-dc733d275f34.png">
@wuomzfx ， 麻烦您看下是什么原因，谢谢

**Comment by wuomzfx** [comment]
再加一个 html-loader 试试
```javascript
{
        test: /\.(html)$/,
        loader: 'html-loader',
        options: {
          interpolate: true,
        }
},
{
        test: /\.(html)$/,
        loader: 'html-layout-loader',
        options: {
          layout: 'index.html'
        }
  }
```

**Comment by baoyadong** [comment]
@wuomzfx 
ok,能运行了，非常感谢

**Comment by baoyadong** [comment]
@wuomzfx ,我在熟悉您的html-loyout-loader的写法，能问下这个loader写的的方法怎么调试吗？我想知道具体每一步会输出什么样的结果？我使用了console.log(), 好像没什么用。

**Comment by wuomzfx** [comment]
@baoyadong 它就是处理html文件并将处理后的文件再交于webpack，你想console.log 得直接去源码里console.log 才能获取到它返回的输出了。  这个loader功能也比较简单，就是能将引用的html 嵌套在 另外一个模版html内部。具体工程化实践也可以参考我另外一个项目：https://github.com/wuomzfx/pure-webpage
