### ISSUE TITLE
作者，您好，方便在代码关键位置加一些注释吗？

### ISSUE THREAD

**Issue by leeboya** [wuomzfx/html-layout-loader#2]
在阅读源码index.js的时候 在
 ```
const reg = new RegExp(`(@${decorator}\\()(.*?)\\)`)
 const regResult = reg.exec(source)
```
的时候就有点看不懂了，可以加点注释说明一些吗，谢谢！

**Comment by wuomzfx** [comment]
就是 正则匹配 @layout(....) 这样。
然后 "layout" 这个占位符 可以自定义，于是就用了模板字符串 ${decorator}

之前写代码时，就几十行，也就偷懒没注释了
